---
title: 'STOR 565: Homework 1'
author: "Brian N. White"
date: "1/10/2022"
output:
  pdf_document: default
  html_document: default
---

```{r load packages}
library(diagram)
library(tidyverse)
```

**Exercise 1**

```{r}
x1 <- c(2, .5, 4., 2)
x2 <- c(x1, rep(1, 4))
x3 <- 1:-2
x4 <- c('Hello','', 'World', '!', 'Hello World!' )
x4
```
**Exercise 2**

```{r}
x0 <- c(1, 0, -1, 2)
x1 <- c(2, .5, 4, 2)


X <- rbind(1:4, x0, x1, rep(1, 4), deparse.level = 0)
X
```


**Exercise 3**

```{r}
y1 <- X[X < 0]
y2 <- X[X > 0 & X < 2]

y1
y2
```

**Exercise 4**

```{r}
students <- data.frame( id      = factor(c("001", "002", "003")), 
                        score_A = c(95, 97, 90),         
                        score_B = c(80, 75, 84)) 

students$id == '003'
students[students$id == '003', ]
```

**Exercise 5**

```{r}
r0 <- c('Sun', 'Mon', 'Tues', 'Weds', 'Thurs', 'Fri', 'Sat')
r1 <- c('', 'NY', 2:6)
r2 <- 7:13
r3 <- c(14, 'MLK', 16:20)
r4 <- 21:27
r5 <- c(28:31, rep('', 3))

cal <- rbind(r0, r1, r2, r3, r4, r5)
cal <- as.data.frame(cal)
cal
```

**Exercise 6**

```{r}
id        <- factor(rep(c("001","002","003"), 2))
subj      <- rep(c("A","B"), each = 3)
score     <- c(95, 97, 90, 80, 75, 84)
students3 <- data.frame(id, subj, score)

#using cut
students3 %>%
  mutate(grade = cut(score, c(0, 80, 90, 100), labels = c('C', 'B', 'A'), right = F))

#directly
students3 %>%
  mutate(grade = ifelse(score < 80, 'C', ifelse(score < 90, 'B', 'A')))
```


**Exercise 7**

```{r}
mu <- apply(X, 2, mean)

X.cent <- t(X) - mu
X.var <- (1/3)*X.cent%*%t(X.cent)
X.var
var(X)
```
**Exercise 8**

```{r}
students3 %>%
  group_by(subj) %>%
  mutate(score.mean = mean(score))
```
**Exercise 9**

```{r exercise 9, bisection method}
bisect <- function(f, lower, upper, tol = 10^-6, maxit = 1000){
  #algorithm conditions
  if(lower >= upper ) {
    stop('lower must be strictly less than upper')
  }
  
  if(sign(f(lower)) == sign(f(upper))) {
    stop('f(lower) and f(upper) must have different signs)')
  }
  
  #begin algorithm
  
  #set counter
  i <- 1
  while(i <= maxit) {
    c <- (lower + upper)/2
    if(f(c) == 0 | (upper - lower)/2 < tol) {
      return(c)
      break
    }
    #increment counter
     i <- i + 1
    #modify lower and upper
      if(sign(f(c)) == sign(f(lower))) {
      lower <- c
    } else {
      upper <- c
    }
  }
  stop('method failed: maximum number of iterations reached')
}

```

```{r}
#function to test bisect on
f <- function(x) x^3 - 2*x - 1
plot(f, xlim = c(-2, 2))
abline(0, 0, col='blue')

root1 <- bisect(f, 1, 2)
root2 <- bisect(f, -.8, 0)
root3 <- bisect(f, -2, -.9)
plot(f, xlim = c(-2, 2))
abline(0, 0, col='blue')

#confirm roots
abline(v = root1, col = 'green')
abline(v = root2, col= 'red')
abline(v = root3, col= 'purple')
```

**Exercise 10**

```{r}
salaries <- read.csv('data/unc_salary_data.csv')

index <- str_which(salaries$dept, 'Stat*')

STOR <- salaries[index,]

STOR %>%
  select(name, age, totalsal)

salaries %>%
  select(name, dept, totalsal) %>%
  filter(totalsal > 200000) %>%
  head()

salaries %>%
  select(name, dept, totalsal) %>%
  group_by(dept) %>%
  summarise(mean_salary = mean(totalsal)) %>%
  filter(grepl('Statistics*', dept))
```
**Exercise 11**

```{r}
data(iris)

iris %>%
  mutate(id = row_number()) %>%
  group_by(Species) %>%
  mutate(subset = cut(sample(row_number()), breaks = 5, labels = 1:5)) %>%
  group_by(subset) %>%
  group_split() -> iris_subsets
  
lapply(iris_subsets, head)
lapply(iris_subsets, function(x) x$id)
lapply(iris_subsets, function(x) table(x$Species))
```

**Exercise 12**

```{r}
salaries %>%
  filter(dept %in% c('Computer Science', 'Mathematics', 'Statistics and Operations Res', 'Physics-Astronomy')) %>%
  mutate(hire_year = as.numeric(str_sub(hiredate, 1, 4))) %>%
  group_by(hire_year, dept) %>%
  summarise(n = n()) %>%
  ggplot(aes(hire_year, n, col = dept, linetype = dept)) +
  geom_line()
```
**Exercise 13**

```{r}
index <- c('Computer Science', 'Mathematics', 'Statistics and Operations Res', 'Physics-Astronomy')

for(i in index){
print(salaries %>%
  filter(dept == i) %>%
  ggplot(aes(x = totalsal)) +
  labs(title = i) + 
  geom_histogram(aes(y = ..density..), binwidth = 15000) +
  geom_density(col = 'red'))
}

salaries %>%
  filter(dept %in% c('Computer Science', 'Mathematics', 'Statistics and Operations Res', 'Physics-Astronomy')) %>%
  ggplot(aes(x = totalsal)) +
  geom_histogram(aes(y = ..density.., fill = dept))

salaries %>%
  filter(dept %in% c('Computer Science', 'Mathematics', 'Statistics and Operations Res', 'Physics-Astronomy')) %>%
  ggplot(aes(x = totalsal, col = dept)) +
  geom_density() 
```

